services:
  - type: web
    name: catzoteam
    env: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: free

    # Environment variables
    envVars:
      - key: SECRET_KEY
        generateValue: true

      # Database URL - add manually from existing database
      - key: DATABASE_URL
        sync: false

      - key: CLOUDINARY_CLOUD_NAME
        sync: false

      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false

      - key: DJANGO_SETTINGS_MODULE
        value: catzoteam_project.settings

      - key: DEBUG
        value: "False"
