services:
  - type: web
    name: catzoteam
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free

    # Add environment variables
    envVars:
      - key: SECRET_KEY
        generateValue: true

      - key: DATABASE_URL
        fromDatabase:
          name: catzoteam-db
          property: connectionString

      - key: CLOUDINARY_CLOUD_NAME
        sync: false

      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false

      - key: DJANGO_SETTINGS_MODULE
        value: catzoteam_project.settings

      - key: DEBUG
        value: "False"

# Define database
databases:
  - name: catzoteam-db
    databaseName: catzoteam
    user: catzoteam
    plan: free
