services:
  - type: web
    name: catzonia
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-eng
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: gunicorn catzoteam_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/4.00/tessdata
